name: Build and publish docker image to dockerHub

on:
  push:
    branches: [main]

jobs:
  build-push-image:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: image/Dockerfile
          tags: weevenetwork/weeve-slack-alert:latest
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
      - name: Image Digest
        run: echo ${{ steps.build-push-image.outputs.digest }}
